---
title: "Olympic Games Analysis"
author: "José Luis Tello"
date: "8/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(scales)
```


```{r}
medals <- read.csv("tokyo2021.csv", header = TRUE)
```

MMMM... I need to change this col names!

```{r}
str(medals)
```

## Data Wrangling

1. Create a frame with new column names

```{r}
tokyo2021 <- rename(medals, 
       country = Team.NOC,
       gold = Gold.Medal,
       silver = Silver.Medal,
       bronze = Bronze.Medal,
       rankbytotal = Rank.by.Total,
       ccode = NOCCode
              )
```


```{r}
tokyo <- as_tibble(tokyo2021)
```


## Data Viz!

```{r}
tokyo %>% 
  group_by(country) %>% 
  count(gold) %>% 
  filter(gold >= 10) %>% 
  ggplot(aes(x = reorder(country, gold), y = gold)) +
  geom_bar(stat = 'identity', 
           size=1, 
           fill="darkgoldenrod2",) +
  geom_text(aes(label = gold),
            vjust = .5, nudge_y = .90, nudge_x = 0.15) +
  labs(x = "Gold Medals",
       y = "Country",
       title = "Countries with the most gold medals") +
  coord_flip() +
  theme_classic() +
  theme(legend.position = "none")

```

```{r}
tokyo %>% 
  group_by(country) %>% 
  count(silver) %>% 
  filter(silver >= 10) %>% 
  ggplot(aes(x = reorder(country, silver), y = silver)) +
  geom_bar(stat = 'identity', 
           size=1,
           fill="azure3") +
  geom_text(aes(label = silver),
            vjust = .5, nudge_y = .90, nudge_x = 0.15) +
  labs(x = "Silver Medals",
       y = "Country",
       title = "Countries with the most silver medals") +
  coord_flip() +
  theme_classic() +
  theme(legend.position = "none")
```


```{r}
tokyo %>% 
  group_by(country) %>% 
  count(bronze) %>% 
  filter(bronze >= 10) %>% 
  ggplot(aes(x = reorder(country, bronze), y = bronze)) +
  geom_bar(stat = 'identity', 
           size=1,
           fill="chocolate3") +
  geom_text(aes(label = bronze),
            vjust = .5, nudge_y = .90, nudge_x = 0.15) +
  labs(x = "Bronze Medals",
       y = "Country",
       title = "Countries with the most Bronze medals") +
  coord_flip() +
  theme_classic() +
  theme(legend.position = "none")
```


```{r}
tokyo %>% 
  group_by(country) %>% 
  count(bronze, sort = TRUE) %>% 
  arrange(desc(bronze)) %>% 
  ggplot(aes(bronze)) +
  geom_histogram() +
  scale_x_reverse()
```

```{r}
tokyo %>% 
  select(country, Total) %>% 
  filter(Total >= 25) %>% 
  arrange(country) %>% 
  ggplot(aes(country, Total)) +
  geom_bar(stat = 'identity')
```


```

